baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cyberdino"
theme = "ananke"

# Tambahkan konfigurasi menu
[menu]
  [[menu.main]]
    identifier = "network"
    name = "Network"
    url = "/network/"
    weight = 1

  [[menu.main]]
    identifier = "data"
    name = "Data"
    url = "/data/"
    weight = 2

  [[menu.main]]
    identifier = "security"
    name = "Security"
    url = "/security/"
    weight = 3

  [[menu.main]]
    identifier = "software"
    name = "Software"
    url = "/software/"
    weight = 4

  [[menu.main]]
    identifier = "web"
    name = "Web"
    url = "/web/"
    weight = 5

  [[menu.main]]
    identifier = "forum"
    name = "Forum"
    url = "/forum/"
    weight = 6

